spring.application.name=product-service
server.port=8081
evaria.services.price-url=http://localhost:8082
evaria.services.media-url=http://localhost:8083
evaria.services.inventory-url=http://localhost:8084
